# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a220c8af5be3c6ce083761de3d6930e4"
name = "my-new-awesome-app"
handle = "my-new-awesome-app-306"
application_url = "https://book-acquired-construct-earn.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://book-acquired-construct-earn.trycloudflare.com/auth/callback",
  "https://book-acquired-construct-earn.trycloudflare.com/auth/shopify/callback",
  "https://book-acquired-construct-earn.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
